### ISSUE TITLE
Error: Cannot read properties of null (reading 'html_content') on 2.0.0

### ISSUE THREAD

**Issue by cromelex** [rishikanthc/markopolis#14] opened 2024-09-09 10:27 UTC
Getting an issue upon updating to 2.0.0.

The /docs endpoint works at http://localhost:8080/docs but on the frontend http://localhost:8080 i am getting a Cannot read properties of null (reading 'html_content') error.

![image](https://github.com/user-attachments/assets/95f05302-6642-429e-bce2-2cb7af567637)

It doesn't even seem to be loading the title as it shows markopolis on the top left corner.

This happens both on a clean empty setup (no consume or mdsync run) or if I run consume or mdsync and actually have .md files in the folder).

I can see the below in the logs

> Error fetching API response: TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:16289:11)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   cause: Error: connect ECONNREFUSED ::1:8000
>       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
>     errno: -111,
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '::1',
>     port: 8000
>   }
> }
> Error fetching or parsing data: TypeError: Cannot read properties of null (reading 'html_content')
>     at load (file:///app/frontend/build/server/chunks/2-DwqWijGm.js:43:52)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async load_server_data (file:///app/frontend/build/server/index.js:1846:18)
>     at async file:///app/frontend/build/server/index.js:3314:18

If you need more of the logs or anything else let me know.

I do see the below error when getting the docker container up:

>  ! markopolis-docs The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested   0.0s

**Comment by cromelex** [comment] 2024-09-09 16:37
To add, I am getting some errors trying to deploy this on my VPS as well, while on my local machine it doesn't seem to be an issue, on my vps I seem to get stuck with a `exec /bin/sh: exec format error`

> 
requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 0.0s

**Comment by rishikanthc** [comment] 2024-09-10 18:53
Got it. Can you try navigating to a page other than the home page and let me know if you see this error ? That would help me debug as I'm not facing this on my local or deployed setup. 
Apologies for the late response. Was traveling

**Comment by cromelex** [comment] 2024-09-10 20:33
Np. I didn't have the chance to test earlier for similar reasons. 

 It happens in all pages - using the same source files as before, and a bind mount, so I can see the .md files are there. But even navigating manually to `/filename` there's no difference.

I've checked and this happens even on a empty server (ie, I spin up a container with `markopolis:latest` and if I navigate to the server I see the same error). So I don't think it's being caused by the mdsync or consume process. The /docs endpoint still works

Happens on my homelab and VPS too, so it isn't machine specific.


I'll post my docker compose just in case I've messed up and can't see it:

```
version: "3.8"
services:
  ##### markopolis docs #####            
  markopolis-docs:
    image: ghcr.io/rishikanthc/markopolis:latest
    container_name: markopolis-docs
    restart: always
    volumes:
      - /home/server/appdata/markopolis/docs/:/app/markdown # bind host mount
    environment:
      - MARKOPOLIS_DOMAIN="https://docs.domain.me"
      - MARKOPOLIS_FRONTEND_URL="https://docs.domain.me"
      - MARKOPOLIS_TITLE="Docs"
      - MARKOPOLIS_MD_PATH=/app/markdown
      - MARKOPOLIS_API_KEY=
 ```

Can I email you the full container log ?

**Comment by cromelex** [comment] 2024-09-10 20:56
I've actually gone ahead and emailed you the logs to your public email address.

**Comment by rishikanthc** [comment] 2024-09-11 02:05
Perfect. Thanks a tonne. The logs were very useful. I think I know what the issue is. I'll work on fixing it.

**Comment by anantone** [comment] 2024-09-16 12:25
Having the same problem.

**Comment by cromelex** [comment] 2024-09-17 22:58
@rishikanthc any idea of when you might be able to fix this?
I'm by no means trying to rush you, just trying to get an idea of the date as there's a couple of notes I need to share online soon. Thanks again!

**Comment by cratedev** [comment] 2024-09-18 11:28
Same problem.

**Comment by rishikanthc** [comment] 2024-09-27 02:15
@cromelex Sorry about the late reply. I was in the middle of moving houses so couldn't get to it sooner. The new release should he done shortly. I just pushed the code to the repo and updated the python package. will upload docker images in a couple hours. My apologies for the delay.

**Comment by cromelex** [comment] 2024-09-27 06:44
> @cromelex Sorry about the late reply. I was in the middle of moving houses so couldn't get to it sooner. The new release should he done shortly. I just pushed the code to the repo and updated the python package. will upload docker images in a couple hours. My apologies for the delay.

Don't apologise, it's your project and your time.

I'll give this a try later and report back. Thanks!

**Comment by cromelex** [comment] 2024-09-27 09:15
Getting an error, only grabbed the log from my phone but can send you the full logs later when I get the chance.

> 2024-09-27 05:48:28,248 INFO spawned: 'node' with pid 38
> node:internal/modules/cjs/loader:1143
>   throw err;
>   ^
> 
>     all values are hidden
> 
> Error: Cannot find module '/app/build'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
>     at Module._load (node:internal/modules/cjs/loader:981:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
>     at node:internal/main/run_main_module:28:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
>     all values are hidden
> 
> Node.js v18.20.4
> 2024-09-27 05:48:28,347 WARN exited: node (exit status 1; not expected)
> 2024-09-27 05:48:29,349 INFO gave up: node entered FATAL state, too many start retries too quickly

**Comment by cromelex** [comment] 2024-09-27 14:53
[markopolis-public-2024-09-27T14-50-45.log](https://github.com/user-attachments/files/17165966/markopolis-public-2024-09-27T14-50-45.log)

Full log attached. Happening on all instances. Thanks

**Comment by rishikanthc** [comment] 2024-09-27 23:52
@cromelex  can you try now ? 
Have pushed all changes a new docker image. I tested it and on my end it seems to be working. The documentation website https://markopolis.app has also been updated and is running. Let me know if this works

**Comment by cromelex** [comment] 2024-09-28 08:18
Will try when I get the chance. I see there's a few changes in the compose/
setup so I'll need to go through that first.

Will provide feedback once I do.

**Comment by cromelex** [comment] 2024-09-28 20:25
@rishikanthc I've re-pulled 3.0.0 and used the environment: in the docker-compose rather than a .env

I can see an API with 404 on localhost: 8080
I can see the markopolis website with a error 500 on :3000. 

The title is "Markopolis" and captions say "none".

environment:
      - API_KEY=longstring
      - POCKETBASE_URL=http://127.0.0.1:8080
      - POCKETBASE_ADMIN_EMAIL=xxx@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=password
      - TITLE=Docs
      - CAP1=caption1
      - CAP2=caption2
      - CAP3=caption3

So it doesn't look like they were read? The pocketbase bits did work at I could see the email in the logs.

When I navigate to localhost:3000 I can see a few errors in the logs starting with: 

> logged in with:  admin@example.com admin123 none none
> login valid
> Error fetching records: ClientResponseError 404: The requested resource wasn't found.
> 

Those aren't the email/password combo I set in t he environment, so could it be the case that your frontend isn't picking up the environment entries properly?

Some mismatch at the moment between the site and the readme, so I exposed 8080, 8090, and 3000.

8080 and 3000 seem to be right ones. 8090 isn't showing anything at all.

What is the 8080 port used for?

Using the local part, I upgraded `pip install --upgrade markopolis` before running mdsync.

I used the previous setup ( MARKOPOLIS_CONFIG_PATH set to the file with domain, path and api key) but got an error about missing API Key first. 
I tried setting them manually, and that seemed to work  (it tried to upload the .md files) but then I get a 404 or 401 error.

I tried using http://localhost:8080 and http://localhost: 3000 but got the errors on both so not entirely sure which I should be using for the local piece.

Do I need to be doing something differently here for either the docker or the local bit?

Thanks,

**Comment by rishikanthc** [comment] 2024-09-28 20:53
I don't think anything is wrong. Initially since there are no markdown files the page throws an error and doesn't find any resource. You're getting the local bit wrong.
You need to set 2 environment variables this time and there's no config file. simply set MARKOPOLIS_DOMAIN to your server domain with protocol and set MARKOPOLIS_API to be the same api key you used in docker.

Can you try this and upload markdown files and then see if it works?

**Comment by cromelex** [comment] 2024-09-28 21:09
> ❯ mdsync
> 2024-09-28 21:59:46.024 | INFO     | markopolis.upload:mdsync:56 - url: home.md
> 2024-09-28 21:59:46.024 | INFO     | markopolis.upload:mdsync:61 - Uploading home.md
> 2024-09-28 21:59:47.037 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload home.md. Status code: 401
> 2024-09-28 21:59:47.037 | INFO     | markopolis.upload:mdsync:56 - url: Apps.md
> 2024-09-28 21:59:47.038 | INFO     | markopolis.upload:mdsync:61 - Uploading Apps.md
> 2024-09-28 21:59:47.096 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload Apps.md. Status code: 401
> 2024-09-28 21:59:47.105 | ERROR    | markopolis.upload:mdsync:80 - Failed to get file list from API. Status code: 401

From the container logs:

> 
> login valid
>     status: 404,
>     data: {
>       code: 404,
>       message: "The requested resource wasn't found.",
>       data: {}
>     }
>   }
> }
> login valid
> ClientResponseError 404: The requested resource wasn't found.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async GET (file:///app/build/server/chunks/_server.ts-5mxdY660.js:8:19)
>     at async render_endpoint (file:///app/build/server/index.js:1185:20)
>     at async resolve2 (file:///app/build/server/index.js:3672:22)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async fetch (file:///app/build/server/index.js:3317:26) {
>   url: '[http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1',](http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1%27,)
>   status: 404,
>   response: {
>     code: 404,
>     message: "The requested resource wasn't found.",
>     data: {}
>   },
>   isAbort: false,
>   originalError: {
>     url: '[http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1',](http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1%27,)
>     status: 404,
>     data: {
>       code: 404,
>       message: "The requested resource wasn't found.",
>       data: {}
>     }
>   }
> }
> logged in with:  admin@example.com admin123 none none
> login valid
> Error fetching records: ClientResponseError 404: The requested resource wasn't found.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async GET (file:///app/build/server/chunks/_server.ts-CxeK7_lb.js:34:22)
>     at async render_endpoint (file:///app/build/server/index.js:1185:20)
>     at async resolve2 (file:///app/build/server/index.js:3672:22)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async fetch (file:///app/build/server/index.js:3317:26) {
>   url: '[http://127.0.0.1:8080/api/collections/mdbase/records?page=1&perPage=200&sort=url',](http://127.0.0.1:8080/api/collections/mdbase/records?page=1&perPage=200&sort=url%27,)
>   status: 404,
>   response: {
>     code: 404,
>     message: "The requested resource wasn't found.",
>     data: {}
>   },
>   isAbort: false,
>   originalError: {
>     url: '[http://127.0.0.1:8080/api/collections/mdbase/records?page=1&perPage=200&sort=url',](http://127.0.0.1:8080/api/collections/mdbase/records?page=1&perPage=200&sort=url%27,)
>     status: 404,
>     data: {
>       code: 404,
>       message: "The requested resource wasn't found.",
> login valid
>       data: {}
>     }
>   }
> }
> ClientResponseError 404: The requested resource wasn't found.
>     at file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32687
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async GET (file:///app/build/server/chunks/_server.ts-5mxdY660.js:8:19)
>     at async render_endpoint (file:///app/build/server/index.js:1185:20)
>     at async resolve2 (file:///app/build/server/index.js:3672:22)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async fetch (file:///app/build/server/index.js:3317:26) {
>   url: '[http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1',](http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1%27,)
>   status: 404,
>   response: {
>     code: 404,
>     message: "The requested resource wasn't found.",
>     data: {}
>   },
>   isAbort: false,
>   originalError: {
>     url: '[http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1',](http://127.0.0.1:8080/api/collections/tags/records?page=1&perPage=500&skipTotal=1%27,)
>     status: 404,
>     data: {
>       code: 404,
>       message: "The requested resource wasn't found.",
>       data: {}
>     }
>   }
> }
> logged in with:  admin@example.com admin123 none none
> Error: Data returned from `load` while rendering / is not serializable: Cannot stringify arbitrary non-POJOs (data.err)
>     at get_data (file:///app/build/server/index.js:2541:11)
>     at render_response (file:///app/build/server/index.js:2297:28)
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async render_page (file:///app/build/server/index.js:3059:12)
>     at async resolve2 (file:///app/build/server/index.js:3675:24)
>     at async respond (file:///app/build/server/index.js:3567:22)
>     at async Array.ssr (file:///app/build/handler.js:1262:3)
> login valid

The title and so on aren't changing at all, the title doesn't match what I input on the environment ?
I tried placing them on the .env instead, but it still looks like the container isn't reading them and it's taking the defaults instead, ie what you specified on the dockerfile?
```
ARG POCKETBASE_ADMIN_EMAIL=admin@example.com
ARG POCKETBASE_ADMIN_PASSWORD=admin123
ARG POCKETBASE_URL=http://127.0.0.1:8080
ARG TITLE=Markopolis
ARG API_KEY=test
ARG CAP1=none
ARG CAP2=none
ARG CAP3=none

```
![image](https://github.com/user-attachments/assets/387b4a59-48ee-4515-bed8-ed1784ee4af8)

**Comment by rishikanthc** [comment] 2024-09-28 21:17
Hmm.. That's weird. can you give me the docker compose you used ?

**Comment by cromelex** [comment] 2024-09-28 21:19
I just tried using the api_key test locally, and that did something.

So it confirms the container isn't taking the environment values I am putting on the docker compose or the .env.

[❯ mdsync
2024-09-28 22:14:09.249 | INFO     | markopolis.upload:mdsync:56 - url: home.md
2024-09-28 22:14:09.249 | INFO     | markopolis.upload:mdsync:61 - Uploading home.md
2024-09-28 22:14:09.338 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded home.md
2024-09-28 22:14:09.338 | INFO     | markopolis.upload:mdsync:56 - url: Apps.md
2024-09-28 22:14:09.338 | INFO     | markopolis.upload:mdsync:61 - Uploading Apps.md
2024-09-28 22:14:09.402 | ERROR    | markopolis.upload:mdsync:68 - Failed to upload Apps.md. Status code: 500](url)

I don' t know it failed.

Restarted the container and then tried again, that did the upload:

> ❯ mdsync
> 2024-09-28 22:17:33.172 | INFO     | markopolis.upload:mdsync:56 - url: home.md
> 2024-09-28 22:17:33.173 | INFO     | markopolis.upload:mdsync:61 - Uploading home.md
> 2024-09-28 22:17:34.004 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded home.md
> 2024-09-28 22:17:34.004 | INFO     | markopolis.upload:mdsync:56 - url: Apps.md
> 2024-09-28 22:17:34.004 | INFO     | markopolis.upload:mdsync:61 - Uploading Apps.md
> 2024-09-28 22:17:34.027 | INFO     | markopolis.upload:mdsync:66 - Successfully uploaded Apps.md

![image](https://github.com/user-attachments/assets/114849d7-b9c6-4182-9687-3866be4ab715)

**Comment by rishikanthc** [comment] 2024-09-28 21:22
Got it. Thanks for this ! Helps me debug. I'm looking into this now. Will fix this shortly.

**Comment by cromelex** [comment] 2024-09-28 21:29
> Hmm.. That's weird. can you give me the docker compose you used ?

```
services:
  ##### markopolis docs #####          
  markopolis-docs:
    image: ghcr.io/rishikanthc/markopolis:3.0.0
    container_name: markopolis-docs
    restart: always
    volumes:
      - /home/me/appdata/markopolis/server/docs/:/app/pb # bind host mount
    environment:
      - API_KEY=alongstringthatisnttest
      - POCKETBASE_URL=http://127.0.0.1:8080
      - POCKETBASE_ADMIN_EMAIL=xxx@gmail.com
      - POCKETBASE_ADMIN_PASSWORD=password
      - TITLE=Docs
      - CAP1=caption1
      - CAP2=caption2
      - CAP3=caption3
    ports:
      - 8080:8080
      - 3000:3000
 ```

**Comment by rishikanthc** [comment] 2024-09-28 22:13
Just fixed this. Since I was building the app during the image building it froze the env variables used during build.
So now as a consequence building happens on image start. The initial start time of the image will be longer as it needs to finish building the app.
This should fix the env variables not reading properly. Can you confirm so i can close this issue ?

**Comment by cromelex** [comment] 2024-09-28 22:35
> Just fixed this. Since I was building the app during the image building it froze the env variables used during build. So now as a consequence building happens on image start. The initial start time of the image will be longer as it needs to finish building the app. This should fix the env variables not reading properly. Can you confirm so i can close this issue ?

Can confirm that's fixed. Cheers!

![Screenshot_20240928-233333](https://github.com/user-attachments/assets/f375c71a-382c-4fcf-b575-ab9b738c2be9)

**Closed** 2024-09-29 00:11 UTC
